.link
# https://4sysops.com/archives/repadmin-vs-powershell-replication-cmdlets/
# https://learn.microsoft.com/en-us/powershell/module/activedirectory/?view=windowsserver2025-ps

<#
PowerShell equivalents for Repadmin commands
The following table includes a few replication functions available from both of the tools.

Get replication partner status
repadmin /showrepl
Get-ADReplicationPartnerMetadata

Get Inbound replication queue details
repadmin /queue
Get-ADReplicationQueueOperation

Replicate specific AD objects between domain controllers
repadmin /replsingleobj
Sync-ADObject

Get replication metadata of an AD object
repadmin /showobjmeta
Get-ADReplicationAttributeMetadata

Shows highest committed USN
repadmin /showutdvec
Get-ADReplicationUpToDatenessVectorTable

Displays ISTG details
repadmin /istg *
Get-ADReplicationSite ?filter * | Select-Object InterSiteTopologyGenerator

List all the subnets in the forest
dsquery subnet
Get-ADReplicationSubnet

List the AD sites in the domain
dsquery site
Get-ADReplicationSite
#>


# Get-ADReplicationPartnerMetadata
Get-ADReplicationPartnerMetadata -Target DC2012 -Partition domain | Select-Object Server, @{n = 'Partner'; e = { (Resolve-DnsName $_.PartnerAddress).NameHost } }, LastReplicationAttempt


Get-ADReplicationAttributeMetadata 'DC=Win8,DC=test.local,CN=MicrosoftDNS,DC=DomainDnsZones,DC=test,DC=local' -Server DC2012 -IncludeDeletedObjects -ShowAllLinkedValues | Where-Object { $_.attributename -eq 'dnsTombstoned' }

# Get-ADReplicationFailure
Get-ADReplicationFailure -Target ADC2012 | Select-Object Server, Partner, FirstFailureTime, FailureCount, FailureType

# Get-ADReplicationConnection
Get-ADReplicationConnection -Properties * -Filter * | Select-Object Name, AutoGenerated, InterSiteTransportProtocol, schedule, fromServer | Format-Table

Get-ADReplicationConnection -Identity ADC2012->WIN-H5A3L7FJOB4 -Properties * | Select-Object Name, AutoGenerated, InterSiteTransportProtocol, schedule, fromServer | Format-Table

#Get-ADReplicationSite
Get-ADReplicationSite -Filter * -Properties

# Get-ADReplicationSiteLink

Get-ADReplicationSiteLink -Identity 'd1747afc-df32-45bd-9590-bdc368310949'

# Get-ADReplicationSubnet

Get-ADReplicationSubnet -Filter { Site -eq 'Bangalore' }

# Get-ADReplicationSitelinkBridge

Get-ADReplicationSiteLinkBridge -Identity 'CN=SiteLinkBridge, CN=IP,CN=Inter-Site Transports,CN=Sites,CN=Configuration,DC=test,DC=local'


# Display The Highest Update Sequence Number (USN) on a server
# repadmin /showutdvec localhost dc=contoso, dc=com
Get-ADReplicationUpToDatenessVectorTable localhost -Partition 'dc=contoso, dc=com'
Get-ADReplicationUpToDatenessVectorTable -Target localhost -Partition Default


Get-adreplicationFailure

get-adreplication
Import-Module ActiveDirectory

Get-ADReplicationAttributeMetadata
# Gets the replication metadata for one or more Active Directory replication partners.

Get-ADReplicationConnection
# Returns a specific Active Directory replication connection or a set of AD replication connection objects based on a specified filter.

Get-ADReplicationFailure
# Returns a collection of data describing an Active Directory replication failure.

Get-ADReplicationPartnerMetadata
# Returns the replication metadata for a set of one or more replication partners.

Get-ADReplicationQueueOperation
# Returns the contents of the replication queue for a specified server.

Get-ADReplicationSite
# Returns a specific Active Directory replication site or a set of replication site objects based on a specified filter.

Get-ADReplicationSiteLink
# Returns a specific Active Directory site link or a set of site links based on a specified filter.

Get-ADReplicationSiteLinkBridge
# Gets a specific Active Directory site link bridge or a set of site link bridge objects based on a specified filter.

Get-ADReplicationSubnet
# Gets one or more Active Directory subnets.

Get-ADReplicationUpToDatenessVectorTable
# Displays the highest Update Sequence Number (USN) for the specified domain controller.
